FROM public.ecr.aws/lambda/python:3.11
WORKDIR /var/task
COPY requirements.lambda.txt .
RUN pip install -r requirements.lambda.txt --no-cache-dir --only-binary=:all:
COPY lambda_handler.py .
CMD ["lambda_handler.handler"]
